#!/bin/sh
# swp - suckless webframework - 2024 - MIT License - rhighs <rmontalti.com>

swp_filter() {
	for b in $BL; do
		[ "$b" = "$1" ] && return 0
	done
}

swp_main() {
	$MDHANDLER "$1"
}

swp_menu() {
	echo "<ul>"
	[ -z "$(echo $1 | grep index.md)" ] && echo "<li><a href=\"index.html\">.</a></li>"
	[ "$(dirname "$1")" != "." ] && echo "<li><a href=\"../index.html\">..</a></li>"
	ls "$(dirname "$1")" | sed -e 's,.md$,.html,g' | while read i ; do
		swp_filter "$i" && continue
		NAME=$(echo $i | sed -e 's/\..*$//')
		[ -z "$(echo $i | grep '\..*$')" ] && i="$i/index.html"
		echo "<li><a href=\"$i\">$NAME</a></li>"
	done
	echo "</ul>"
}

swp_page() {
	# Header
	cat << _header_
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${PAGE_TITLE}</title>
<link rel="icon" href="/favicon.png" type="image/png">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"></script>
_header_
	# Stylesheet
	swp_style
	cat << _header_
</head>
<body>
</article>
<header>
<h1 class="headerTitle">
<a href="$(echo $1 | sed -e 's,[^/]*/,../,g' -e 's,[^/]*.md$,index.html,g')">${HEADER_TITLE}</a> 
</h1>
<h4 class="headerSubtitle">${HEADER_SUBTITLE}</h4>
</header>
_header_
	# Menu
	echo "<div id=\"side-bar\">"
	swp_menu "$1"
	echo "</div>"
	# Body
	echo "<div id=\"main\">"
	swp_main "$1"
	echo "</div>"
	# Footer
	cat << _footer_
<div id="footer">
<div class="right"><a href="https://github.com/rhighs/swp">Powered by swp</a></div>
</div>
</article>
</body>
</html>
_footer_
}

swp_style() {
	if [ -f "$CDIR/$STYLE" ]; then
		echo '<style type="text/css">'
		cat "$CDIR/$STYLE"
		echo '</style>'
	fi
}

# Set input dir
IDIR="$(echo $1 | sed -e 's,/*$,,')"
if [ -z "$IDIR" ] || [ ! -d "$IDIR" ]; then
	echo "Usage: swp [dir]"
	exit 1
fi

# Load config file
if [ ! -f "$PWD/swp.conf" ]; then
	echo "Cannot find swp.conf in current directory"
	exit 1
fi
. "$PWD/swp.conf"

# Setup output dir structure
CDIR=$PWD
ODIR="$CDIR/$(basename "$IDIR").static"
rm -rf "$ODIR"
mkdir -p "$ODIR"
cp -rf "$IDIR"/* "$ODIR"
find "$ODIR" -type f -iname '*.md' -delete

# Parse files
cd "$IDIR" || exit 1
find * -iname '*.md' | while read a ; do
	b="$ODIR/$(echo $a | sed -e 's,.md$,.html,g')"
	echo "* $a"
	swp_page "$a" > "$b"
done

exit 0
